# Generated by Django 5.1.1 on 2024-09-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coming_soon_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterSignup',
            new_name='updates',
        ),
    ]
